use_frameworks!

platform :ios, '8.0'

target 'NYPublicTest_Example' do
  pod 'NYPublicTest', :path => '../'

  target 'NYPublicTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
